apiVersion: apps/v1
kind: Deployment
metadata:
  name: workertests-cron
spec:
  selector:
    matchLabels:
      app: workertests-cron
  replicas: 1
  template:
    metadata:
      labels:
        app: workertests-cron
    spec:
      containers:
        - name: worker
          image: renatogroffe/workertests-dotnet8:2
          env:
          - name: WaitingTimeInSeconds
            value: "5"